packages:
  - examples/*
  - '@sensoro-design/*'
  - packages/**/*
  - website
  - scripts
catalog:
  simple-git: ^3.26.0
  taze: ^0.16.7
  tsx: ^4.19.0
  type-fest: ^4.26.0
  typescript: ^5.5.4
  unbuild: ^2.0.0
  vite: ^5.4.3
  vite-plugin-style-import: ^2.0.0
  vitest: ^2.0.5
  zx: ^8.1.5
