packages:
  - examples/*
  - '@sensoro-design/*'
  - packages/**/*
  - website
  - scripts
catalog:
  '@ant-design/plots': ^2.3.1
  '@antv/g2': ^5.2.5
  '@antv/util': ^3.3.8
  '@visactor/vchart': ^1.12.2
  '@visactor/react-vchart': ^1.12.2
  '@antfu/eslint-config': 2.21.2
  '@antfu/ni': ^0.23.0
  '@commitlint/cli': ^19.4.1
  '@commitlint/config-conventional': ^19.4.1
  '@eslint-react/eslint-plugin': ^1.13.0
  '@testing-library/cypress': ^10.0.2
  '@testing-library/jest-dom': ^6.5.0
  '@testing-library/react': ^16.0.1
  '@testing-library/user-event': ^14.5.2
  '@total-typescript/ts-reset': ^0.6.1
  '@types/fs-extra': ^11.0.4
  '@types/lodash-es': ^4.17.12
  '@types/node': ^22.5.3
  '@types/react': ^18.3.5
  '@types/react-dom': ^18.3.0
  '@types/signale': ^1.4.7
  '@vitest/ui': ^2.0.5
  chalk: ^5.3.0
  cross-env: ^7.0.3
  cross-spawn: ^7.0.3
  cypress: ^13.14.1
  cypress-real-events: ^1.13.0
  cypress-vite: ^1.5.0
  execa: ^9.3.1
  eslint: ^8.57.0
  eslint-plugin-cypress: ^3.5.0
  eslint-plugin-react-hooks: ^4.6.2
  eslint-plugin-react-refresh: ^0.4.11
  eslint-plugin-storybook: ^0.8.0
  fast-glob: ^3.3.2
  fs-extra: ^11.2.0
  husky: ^9.1.5
  jsdom: ^25.0.0
  lerna: ^8.1.8
  less: ^4.2.0
  lint-staged: ^15.2.10
  ora: ^8.1.0
  prettier: ^3.3.3
  react: ^18.3.1
  react-dom: ^18.3.1
  rimraf: ^6.0.1
  signale: ^1.4.0
  simple-git: ^3.26.0
  stylelint: ^16.9.0
  stylelint-config-property-sort-order-smacss: ^10.0.0
  stylelint-config-standard: ^36.0.1
  stylelint-order: ^6.0.4
  stylelint-prettier: ^5.0.2
  taze: ^0.16.7
  tsx: ^4.19.0
  type-fest: ^4.26.0
  typescript: ^5.5.4
  unbuild: ^2.0.0
  vite: ^5.4.3
  vite-plugin-style-import: ^2.0.0
  vitest: ^2.0.5
  zx: ^8.1.5
