packages:
  - examples/*
  - '@sensoro-design/*'
  - packages/**/*
  - website
  - scripts
catalog:
  '@antfu/eslint-config': 2.21.2
  '@antfu/ni': ^0.23.0
  '@commitlint/cli': ^19.4.1
  '@commitlint/config-conventional': ^19.4.1
  '@eslint-react/eslint-plugin': ^1.13.0
  chalk: ^5.3.0
  cross-env: ^7.0.3
  cross-spawn: ^7.0.3
  execa: ^9.3.1
  fast-glob: ^3.3.2
  fs-extra: ^11.2.0
  husky: ^9.1.5
  jsdom: ^25.0.0
  lerna: ^8.1.8
  less: ^4.2.0
  lint-staged: ^15.2.10
  simple-git: ^3.26.0
  taze: ^0.16.7
  tsx: ^4.19.0
  type-fest: ^4.26.0
  typescript: ^5.5.4
  unbuild: ^2.0.0
  vite: ^5.4.3
  vite-plugin-style-import: ^2.0.0
  vitest: ^2.0.5
  zx: ^8.1.5
