import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  plotsSidebar: [
    { type: 'autogenerated', dirName: 'plots' },
  ],
  chartsSidebar: [
    { type: 'autogenerated', dirName: 'charts' },
  ],
};

export default sidebars;
